version: '3.9'

services:
  db:
    image: postgres:15
    container_name: testovoe_db_app
    env_file:
      - .env-four-testing
    command: -p 5432
    expose:
      - 5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:7
    container_name: testovoe_redis
    env_file:
      - .env-four-testing

  testovoe_app:
    build:
      context: .
    env_file:
      - .env-four-testing
    container_name: testovoe_app
    command: bash -c "alembic upgrade head && gunicorn src.api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
    - 9999:8000
    depends_on:
      - db
      - redis
      - celery
      
      
  celery:
    build:
      context: .
    env_file:
      - .env-four-testing
    container_name: testovoe_celery
    command: bash -c "celery -A src.broker.tasks:celery worker --loglevel=INFO && python3 src/parser/main.py"


  testovoe_celery_beat:
    build:
      context: .
    container_name: testovoe_celery_beat
    depends_on:
      - testovoe_app
      - celery
      - redis
    command: celery -A src.broker.tasks:celery beat --loglevel=INFO

    env_file:
      - .env-four-testing