"""change key

Revision ID: 969796161a6e
Revises: b0bbae01bb4a
Create Date: 2024-01-21 11:17:43.767671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969796161a6e'
down_revision: Union[str, None] = 'b0bbae01bb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_region_id_fkey', 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key('city_region_id_fkey', 'city', 'city', ['region_id'], ['id'])
    # ### end Alembic commands ###
